<?php
if ( ! defined( 'ABSPATH' ) ) exit;

define( 'SMUZSFTW_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

define( 'SMUZSFTW_PLUGIN_URL', plugins_url( '',plugin_basename( __FILE__ ) ) );

define( 'SMUZSFTW_PLUGIN_DIR_NAME', dirname( plugin_basename( __FILE__ ) ) );

define( 'SMUZSFTW_PLUGIN_INCLUDE_ADMIN_DIRECTORY_NAME', 'admin/includes' );

define( 'SMUZSFTW_PLUGIN_INCLUDE_PUBLIC_DIRECTORY_NAME', 'public/includes' );

define( 'SMUZSFTW_PLUGIN_VIEW_DIRECTORY_NAME', 'views' );

define( 'SMUZSFTW_PLUGIN_CSS_DIRECTORY_NAME', 'css' );

define( 'SMUZSFTW_PLUGIN_JS_DIRECTORY_NAME', 'js' );

define( 'SMUZSFTW_PLUGIN_ADMIN_DIRECTORY', SMUZSFTW_PLUGIN_PATH . 'admin' . DIRECTORY_SEPARATOR );

define( 'SMUZSFTW_PLUGIN_PUBLIC_DIRECTORY', SMUZSFTW_PLUGIN_PATH . 'public' . DIRECTORY_SEPARATOR );

define( 'SMUZSFTW_PLUGIN_INCLUDE_ADMIN_DIRECTORY', SMUZSFTW_PLUGIN_PATH .
									  	SMUZSFTW_PLUGIN_INCLUDE_ADMIN_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZSFTW_PLUGIN_VIEW_DIRECTORY', SMUZSFTW_PLUGIN_PATH .
									  	SMUZSFTW_PLUGIN_VIEW_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZSFTW_PLUGIN_CSS_DIRECTORY', SMUZSFTW_PLUGIN_PATH .
									  	SMUZSFTW_PLUGIN_CSS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZSFTW_PLUGIN_JS_DIRECTORY', SMUZSFTW_PLUGIN_PATH .
									  	SMUZSFTW_PLUGIN_JS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZSFTW_PLUGIN_MAIN_FILE', SMUZSFTW_PLUGIN_PATH . 'SMUZSFTW.php' );

define(  'SMUZSFTW_SHORTCODE', 'Twitterfeed' );

define( 'SMUZSFTW_PLUGIN_VERSION', '1.0' );